apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: participant-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      serviceAccountName: default-editor
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:2.331.0
          imagePullPolicy: IfNotPresent
          env:
            - name: REPO_URL
              value: "https://github.com/moni3004-boop/MLOPS-project"
            - name: RUNNER_TOKEN
              value: "B6GIDRW575FFLVDTGW3SOPLJTSNOE"
            - name: RUNNER_NAME
              value: "kubeflow-runner-17"
            - name: RUNNER_LABELS
              value: "kubeflow,linux"
          command: ["/bin/bash", "-lc"]
          args:
            - |
              set -e
              ./config.sh \
                --url "$REPO_URL" \
                --token "$RUNNER_TOKEN" \
                --name "$RUNNER_NAME" \
                --labels "$RUNNER_LABELS" \
                --unattended \
                --replace
              exec ./run.sh
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "3Gi"

            