apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: adult-income-katib-text-emptydir-v2
  namespace: participant-17
spec:
  maxTrialCount: 1
  parallelTrialCount: 1
  maxFailedTrialCount: 1

  objective:
    type: minimize
    goal: 0.4
    objectiveMetricName: val_log_loss_best
    additionalMetricNames:
      - val_accuracy
      - val_f1
      - test_accuracy
      - test_f1

  algorithm:
    algorithmName: random

  parameters:
    - name: dummy
      parameterType: categorical
      feasibleSpace:
        list: ["x"]

  metricsCollectorSpec:
    collector:
      kind: File
    source:
      fileSystemPath:
        path: /mnt/katib
        format: TEXT

  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: dummy
        description: required
        reference: dummy

    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        backoffLimit: 2
        template:
          spec:
            restartPolicy: Never
            containers:
              - name: training-container
                image: busybox:1.36
                command: ["sh", "-c"]
                volumeMounts:
                  - name: katib-metrics
                    mountPath: /mnt/katib
                args:
                  - |
                    set -e
                    echo "dummy=${trialParameters.dummy}" > /mnt/katib/dummy.txt

                    # write metrics twice (avoid race)
                    for i in 1 2; do
                      printf "%s\n" \
                        "val_log_loss_best 0.3035" \
                        "val_accuracy 0.8123" \
                        "val_f1 0.7011" \
                        "test_accuracy 0.8044" \
                        "test_f1 0.6922" \
                        > /mnt/katib/metrics
                      sleep 2
                    done

                    sleep 300
            volumes:
              - name: katib-metrics
                emptyDir: {}